
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Mar 04 11:51:08 BOT 2017
//----------------------------------------------------

package sql;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int WHERE = 4;
  public static final int FROM = 3;
  public static final int AND = 7;
  public static final int SELECT = 2;
  public static final int OR = 8;
  public static final int EQUAL = 10;
  public static final int QUOTES = 15;
  public static final int SEMI = 12;
  public static final int ALL = 14;
  public static final int ON = 6;
  public static final int NOT_EQUAL = 11;
  public static final int TRUE = 18;
  public static final int ID = 17;
  public static final int COLOM = 9;
  public static final int NUM = 16;
  public static final int EOF = 0;
  public static final int FALSE = 19;
  public static final int error = 1;
  public static final int DOT = 13;
  public static final int JOIN = 5;
}

