
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Dec 12 13:32:09 EST 2016
//----------------------------------------------------

package sql;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 35;
  public static final int INCREMENT = 27;
  public static final int OVER = 32;
  public static final int GE = 21;
  public static final int SEMI = 38;
  public static final int LPAREN = 33;
  public static final int INT = 5;
  public static final int FOR = 14;
  public static final int MINUS = 30;
  public static final int DECREMENT = 29;
  public static final int RPAREN = 34;
  public static final int AND = 25;
  public static final int LT = 22;
  public static final int OR = 26;
  public static final int NUM = 3;
  public static final int PLUS = 28;
  public static final int ASSIGN = 18;
  public static final int MAIN = 12;
  public static final int IF = 8;
  public static final int ID = 2;
  public static final int LE = 20;
  public static final int EOF = 0;
  public static final int BOOLEAN = 4;
  public static final int RETURN = 10;
  public static final int RBRACKET = 36;
  public static final int TRUE = 6;
  public static final int error = 1;
  public static final int VOID = 11;
  public static final int EQ = 19;
  public static final int TIMES = 31;
  public static final int COLOM = 37;
  public static final int PUTS = 17;
  public static final int ELSE = 9;
  public static final int WHILE = 13;
  public static final int GETS = 16;
  public static final int DIFF = 24;
  public static final int FALSE = 7;
  public static final int GT = 23;
  public static final int DO = 15;
}

